trigger:
- main

pool:
  name: 'COMP367-Windows'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.x'
  inputs:
    packageType: SDK
    version: '8.x'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    solution: '**/*.sln'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=Release'

- task: NuGetCommand@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'
  inputs:
    artifactsFeeds: 'Feed4Lab4'

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeed: 'Feed4Lab4'
