trigger:
- main

pool:
  name: 'COMP367-Windows' 

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 8.x'
  inputs:
    packageType: SDK
    version: '8.x'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    solution: 'Library4Lab4Q1.sln'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'Library4Lab4Q1.sln'
    msbuildArgs: '/p:Configuration=Release'

- task: DotNetCoreCLI@2 # Changed from NuGetCommand@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    projects: 'Library4Lab4Q1/StringLibrary/StringLibrary.csproj'
    versioningSource: 'userSpecified'
    version: '1.0.0'

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Feed4Lab4'
    allowPackageConflicts: true
