trigger:
- main

pool:
  name: 'COMP367-Windows'

variables:
  buildConfiguration: 'Release'
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '0'
  versionSuffix: ''
  packageVersion: '$(majorVersion).$(minorVersion).$(patchVersion)$(versionSuffix)'
  dotnetVersion: '8.0.100' # Explicitly specify the .NET 8 SDK version

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate with Azure Artifacts'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    solution: 'Library4Lab4Q1.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'Library4Lab4Q1.sln'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:TargetFramework=net8.0'
    platform: 'Any CPU'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: 'Library4Lab4Q1/StringLibrary/StringLibrary.csproj'
    configuration: '$(buildConfiguration)'
    versioningSource: 'userSpecified'
    version: '1.0.0'
    packageVersion: '$(packageVersion)'
    arguments: '--output $(Build.ArtifactStagingDirectory) /p:TargetFramework=net8.0'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Feed4Lab4'
    allowPackageConflicts: true
    verbosityPush: 'Detailed'
